/*
 * This source file was generated by the Gradle 'init' task
 */

import java.util.Random;
import java.util.Scanner;

public class SlotMachine {

    public static void main(String[] args) {
        /*
		 * This program will act as a simple slot machine game. The program will 
		 * 	randomly generate three numbers between 0 and 9, display them side by 
		 * 	side like a slot machine, and determine whether the player has won 
		 * 	based on the matching numbers.
		 * */

        // Instantiate scanner
        Scanner scanner = new Scanner(System.in);

        // Instantiate random numbers [0 - 9]
        Random random = new Random();
        int num1, num2, num3;

        // Declare point constants
        final int JACKPOT_VALUE = 100;
        final int MATCH_VALUE = 5;
        final int LOSS_VALUE = 0;

        // Declare result variables
        int jackpots = 0;
        int matches = 0;
        int losses = 0;

        // Declare user input variable
        char choice;

        // Iterate each new number generation until user decided to exit the program
        do {
            // Clear console on any existing text
            // 	BUMMER I hoped this would have been an easy thing to add.

            // Generate new random numbers
            num1 = random.nextInt(10);
            num2 = random.nextInt(10);
            num3 = random.nextInt(10);

            // Print results
            System.out.println(num1 + " | " + num2 + " | " + num3);

            // Check results
            if (num1 == num2 && num1 == num3) {
                System.out.println("JACKPOT!!!!!!! All three numbers match!");
                jackpots++;
            } else if (num1 == num2 || num2 == num3 || num1 == num3) {
                System.out.println("You got a match! Two numbers are the same!");
                matches++;
            } else {
                System.out.println("No match. Try again!");
                losses++;
            }

            System.out.print("Do you want to play again? (y/n): ");
            choice = scanner.next().charAt(0);
        } while (choice == 'y' || choice == 'Y');

        // Calculate total points
        int totalPoints = (jackpots * JACKPOT_VALUE) + (matches * MATCH_VALUE) + (losses * LOSS_VALUE);

        // Print farewell and results
        System.out.println("\n###################");
        System.out.println("Thanks for playing!\n\nHere are your results: \nJackpots: "
                + jackpots + "\nMatches:  " + matches + "\nLosses:   " + losses
                + "\n\nTotal Points: " + totalPoints);

        // Close scanner
        scanner.close();
    }
}
